"""Shared constants for the hatchery project."""

# Roles used in the makerspace
ROLE_USER = 'User'
ROLE_COLLABORATOR = 'Collaborator'
ROLE_TEAM_MEMBER = 'Team Member'
ROLE_STAFF = 'Staff'

ROLES = [ROLE_USER, ROLE_COLLABORATOR, ROLE_TEAM_MEMBER, ROLE_STAFF]

# Team Lead is a flag that only applies to Team Members
TEAM_LEAD_ELIGIBLE_ROLE = ROLE_TEAM_MEMBER

# Machine types
MACHINE_TYPE_LASER = 'Laser'
MACHINE_TYPE_VINYL = 'Vinyl'
MACHINE_TYPE_WOODWORKING = 'Woodworking'
MACHINE_TYPE_TEXTILE = 'Textile'
MACHINE_TYPE_METALWORKING = 'Metalworking'
MACHINE_TYPE_3D_PRINTING = '3D Printing'
MACHINE_TYPE_ELECTRONICS = 'Electronics'

MACHINE_TYPES = [
	MACHINE_TYPE_LASER,
	MACHINE_TYPE_VINYL,
	MACHINE_TYPE_WOODWORKING,
	MACHINE_TYPE_TEXTILE,
	MACHINE_TYPE_METALWORKING,
	MACHINE_TYPE_3D_PRINTING,
	MACHINE_TYPE_ELECTRONICS,
]
